version: "3.8"

services:
  db:
    image: postgres:17.5-bookworm
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ego
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  db_test:
    image: postgres:17.5-bookworm
    container_name: postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: ego
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database_test
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  pgdata_test:
